version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      productId: 964
      subProductId: 2163
      environment: Production
      token: 4f7f1545-b73c-42c0-9d45-c9a8a0d5074d
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              wget https://app.armorcode.com/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate
