version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      productId: 1270
      subProductId: 3211
      environment: Staging
      token: 1947c337-5958-499e-b421-ca3c63315d45
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              wget https://app.armorcode.com/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate
